class JWTAuth:
    def __init__(self):
        ...

    def _create_access_token(self, payload: dict) -> str:
        ...

    def _create_refresh_token(self, payload: dict) -> str:
        ...

    def tokens(self, payload):
        ...

    def validate_token(self, token):
        ...
