"""upd

Revision ID: 29fc491c5f54
Revises: 5377450aa42a
Create Date: 2024-05-30 15:51:38.636085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29fc491c5f54'
down_revision: Union[str, None] = '5377450aa42a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issued_tokens',
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('subject', sa.Uuid(), nullable=False),
    sa.Column('revoke', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['subject'], ['users.id'], ),
    sa.PrimaryKeyConstraint('jti')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issued_tokens')
    # ### end Alembic commands ###
