"""add fields

Revision ID: 44dbf2b02e1a
Revises: c694c51890d9
Create Date: 2024-06-05 19:01:54.855116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44dbf2b02e1a'
down_revision: Union[str, None] = 'c694c51890d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'specialists', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'specialists', type_='unique')
    # ### end Alembic commands ###
