"""add cascade delete

Revision ID: ea3b7fd01473
Revises: 4ad55ec25700
Create Date: 2024-06-15 13:49:32.698373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea3b7fd01473'
down_revision: Union[str, None] = '4ad55ec25700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('appointments_user_id_fkey', 'appointments', type_='foreignkey')
    op.drop_constraint('appointments_slot_id_fkey', 'appointments', type_='foreignkey')
    op.drop_constraint('appointments_specialist_id_fkey', 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'appointments', 'schedule_slots', ['slot_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'appointments', 'specialists', ['specialist_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('issued_tokens_subject_fkey', 'issued_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'issued_tokens', 'users', ['subject'], ['id'], ondelete='CASCADE')
    op.drop_constraint('schedule_slots_specialist_id_fkey', 'schedule_slots', type_='foreignkey')
    op.create_foreign_key(None, 'schedule_slots', 'specialists', ['specialist_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('specialists_user_id_fkey', 'specialists', type_='foreignkey')
    op.create_foreign_key(None, 'specialists', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'specialists', type_='foreignkey')
    op.create_foreign_key('specialists_user_id_fkey', 'specialists', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'schedule_slots', type_='foreignkey')
    op.create_foreign_key('schedule_slots_specialist_id_fkey', 'schedule_slots', 'specialists', ['specialist_id'], ['id'])
    op.drop_constraint(None, 'issued_tokens', type_='foreignkey')
    op.create_foreign_key('issued_tokens_subject_fkey', 'issued_tokens', 'users', ['subject'], ['id'])
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key('appointments_specialist_id_fkey', 'appointments', 'specialists', ['specialist_id'], ['id'])
    op.create_foreign_key('appointments_slot_id_fkey', 'appointments', 'schedule_slots', ['slot_id'], ['id'])
    op.create_foreign_key('appointments_user_id_fkey', 'appointments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
